### ISSUE TITLE
Thank you for completing your ballot! (final screen) title text

### ISSUE THREAD

**Issue by cjziegle** [mpk2/VoteBoxUI#13]
The title should be changed from "Thank you for completing your ballot!" to "Thank you for completing your ballot. Now you need to cast your ballot!" Keep the same font size and bold text, but add underlining to "Now you need to cast your ballot!"

**Comment by mpk2** [comment]
I've changed it so it looks like

![image](https://cloud.githubusercontent.com/assets/7244717/9634809/fe8c8cb6-5158-11e5-8d83-4e6406073e10.png)

On this page, there's currently not an easy way to exit. What I've implemented is a 30 second pause before the program auto-exits. I was hoping to get your input on that (length of that pause) since that's almost certainly going to need to be the way we handle it in the actual setup unless we include a button of some sort to exit (just another thing the user has to deal with...)
